apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsbox
  template:
    metadata:
      labels:
        app: nsbox
    spec:
      containers:
        - name: nsbox
          image: ghcr.io/python-discord/nsbox:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8060
          securityContext:
            privileged: true
          volumeMounts:
            - name: nsbox-user-base-volume
              mountPath: /nsbox/user_base
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - >-
                    PYTHONUSERBASE=/nsbox/user_base
                    pip install --user --upgrade
                    anyio[trio]~=3.6
                    arrow~=1.2
                    attrs~=22.2
                    beautifulsoup4~=4.11
                    einspect~=0.5
                    fishhook~=0.2
                    forbiddenfruit~=0.1
                    fuzzywuzzy~=0.18
                    lark~=1.1
                    matplotlib~=3.6
                    more-itertools~=9.0
                    networkx~=3.0
                    numpy~=1.24
                    pandas~=1.5
                    pendulum~=2.1
                    python-dateutil~=2.8
                    pyyaml~=6.0
                    scipy~=1.10
                    sympy~=1.11
                    toml~=0.10
                    typing-extensions~=4.4
                    tzdata~=2022.7
                    yarl~=1.8
      volumes:
        - name: nsbox-user-base-volume
          hostPath:
            path: /nsbox_dep_cache
            type: DirectoryOrCreate
