name: main

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  lint:
    uses: ./.github/workflows/lint.yaml
  test:
    uses: ./.github/workflows/test.yaml
    needs: build
    with:
      artifact: ${{ needs.build.outputs.artifact }}
      version: ${{ needs.build.outputs.version }}
  deploy:
    uses: ./.github/workflows/deploy.yaml
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
    needs: [build, lint, test]
    with:
      artifact: ${{ needs.build.outputs.artifact }}
      version: ${{ needs.build.outputs.version }}
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
